# Generated by Django 5.0 on 2023-12-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_content',
            new_name='Review',
        ),
    ]
